server:
  port: 8080

spring:
  #thymeleaf
  thymeleaf:
    cache: false

  #数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/employment?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useInformationSchema=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml